### ISSUE TITLE
occasional key error when building score tables

### ISSUE THREAD

**Issue by Alex-Markham** [felixleopoldo/cstrees#38]
Here's the error trace:

> Depth=2, working on node 9: 100%|████████████████████████| 10/10 [00:00<00:00, 2662.88it/s]
> Context score tables: 100%|████████████████████████████| 10/10 [00:00<00:00, 129.15it/s]
> Creating #stagings tables: 100%|█████████████████████████| 10/10 [00:00<00:00, 8328.64it/s]
> Order score tables:  60%|███████████████████▌              | 6/10 [00:00<00:00, 405.12it/s]
> Traceback (most recent call last):
>   File "<string>", line 17, in __PYTHON_EL_eval
>   File "/home/alex/projects/cstrees/code/bug_report/reproduce_bug.py", line 28, in <module>
>     est = learn_synth_cstree(data)
>   File "/home/alex/projects/cstrees/code/bug_report/reproduce_bug.py", line 13, in learn_synth_cstree
>     score_table, context_scores, _ = sc.order_score_tables(
>   File "/home/alex/projects/cstrees/code/src/cstrees/scoring.py", line 521, in order_score_tables
>     staging_unnorm_post += context_scores["scores"][var][stage_context]
> KeyError: '0=1,3=1'

I've saved the data set that resulted in this, and wrote a minimal script to reproduce it. I'll push them to a branch now.

**Comment by Alex-Markham** [comment]
fixed in commit 696a7ab
